### ISSUE TITLE
how to run

### ISSUE THREAD

**Issue by dovahkinnn** [tito/kaki#1]
this app maybe good but little information and document or video  how to we use  how to run  debug=1  we dont know please help

**Comment by ghost** [comment]
Can you be specific for what operating system that you used?

Because some people do a different implementation.

Or you can join Kivy discord channel.
https://discord.com/invite/eT3cuQp

**Comment by dovahkinnn** [comment]
Windows10

**Comment by ghost** [comment]
check

https://github.com/prsfx/kaki-on-windows

<br>

you need to aware to set your configuration.

By default, kaki will fired the app from kivy.app App

<br>

There's two examples for that link.

**Comment by dovahkinnn** [comment]
its work thank you

**Comment by ghost** [comment]
Good to know, pleaes close the issues. Thank you
