### ISSUE TITLE
Items drawn are shown twice

### ISSUE THREAD

**Issue by rvanlaar** [tito/kaki#10]
I followed the Pong tutorial from Kivy. The game works as intended.
When integrating kaki all items from the .kv file are shown twice.

A small code example with only the ball  from pong is here:
https://gist.github.com/rvanlaar/c519b77a70074c3d20bc6783e21e79a6

How can I configure Kaki to show items only once?

**Comment by ramayanbindas** [comment]
I encounter a same issue which running a kivymd programme in windows 10.

**Comment by ramayanbindas** [comment]
### Issue Solved
**How ever I manage to solve a little bit issue as you mention**
Same I issue I got during doing the hot reload, but after try and error and digging into bit details I figure out the issue and the solution works for me.
The link of the demo: https://github.com/ramayanbindas/Kivymd_hotreload_demo

**Comment by rvanlaar** [comment]
For others:

Items were shown twice because my `kv` was registered twice. 

1. Kivy will automatically load a `kv` file that has the same name as the `py` one.
2. `pong.kv` was registered in KV_FILES.

Solution is to make sure it's not registered twice. I.e. rename the kv to something else, or disable the automatic loading.
