### ISSUE TITLE
Which key is keycode 286?

### ISSUE THREAD

**Issue by rvanlaar** [tito/kaki#11]
Keycode 286 is used here to reload the application:
https://github.com/tito/kaki/blob/94dc664ff898457040995af87d03aaded45230e1/kaki/app.py#L91

Which key is it?

**Comment by tito** [comment]
F5 !

**Comment by rvanlaar** [comment]
Thanks, made a PR so others new to the project can find it.
https://github.com/tito/kaki/pull/13
