### ISSUE TITLE
Ho to run on linux

### ISSUE THREAD

**Issue by Vampirebat** [tito/kaki#3]
if i have a main.kv and a main.py and my first class is MainApp(MDApp).

How do i get this to work... i have watched the only video i can find on this and im confuesd and i need this.

**Comment by rvanlaar** [comment]
It works.

Steps: 
- Install kivy and kaki
- Checkout kaki: https://github.com/tito/kaki.git
- cd kaki/examples/livedemo
- DEBUG=1 python3 main.py`
- Edit and save the live/ui.py file 

Voila
